// Explicit re-exports (not `export *`) so Node's ESM loader can statically
// detect every named export when the server runs the TS sources via tsx.
export { GAMES, gameById } from "./types";
export type {
  GameId,
  RoomPhase,
  Player,
  GameMeta,
  ChatMessage,
  RoomState,
} from "./types";
export type {
  PlayerIdentity,
  CreateRoomPayload,
  JoinRoomPayload,
  JoinResult,
  UpdateSettingsPayload,
  ClientToServerEvents,
  ServerToClientEvents,
  SocketData,
} from "./protocol";
export {
  DEFAULT_SETTINGS,
  BOMB_BOUNDS,
  BOMB_DIFFICULTIES,
  BOMB_BONUS_ALPHABET,
  CN_WORDS,
  D9_BOUNDS,
  PB_CATEGORIES,
  PB_BOUNDS,
  PB_DEFAULT_CATEGORIES,
  SF_BOUNDS,
  UNO_BOUNDS,
  sanitizeBombParty,
  sanitizeCodenames,
  sanitizeDevine9,
  sanitizePetitBac,
  sanitizeSpyfall,
  sanitizeUno,
  sanitizeSettings,
} from "./settings";
export type {
  BombPartySettings,
  CodenamesSettings,
  Devine9Settings,
  PetitBacSettings,
  SpyfallSettings,
  UnoSettings,
  AllSettings,
} from "./settings";
export { bullHeads, LL_VALUES, LL_COUNTS, LL_CARD_ORDER, LL_TOKENS_TO_WIN, SANDBOX_SHAPES, UNO_COLORS, unoCardPoints } from "./games";
export {
  CHATEAU_CARDS,
  CHATEAU_SHIELDS,
  CHATEAU_FACEDOWN,
  CHATEAU_START,
  chateauCardById,
  chateauFamilyCounts,
  chateauSwitchesMessenger,
} from "./chateauCards";
export type {
  ChateauShield,
  ChateauDeck,
  ChateauFx,
  ChateauPos,
  ChateauScore,
  ChateauCard,
} from "./chateauCards";
export type {
  Language,
  BombPartyView,
  BombPartyAction,
  PetitBacStage,
  PetitBacCell,
  PetitBacReviewCell,
  PetitBacView,
  PetitBacAction,
  SixPlayerPublic,
  SixTurnEntry,
  SixQuiPrendView,
  SixQuiPrendAction,
  CodenamesTeam,
  CodenamesCardColor,
  CodenamesRole,
  CodenamesPhase,
  CodenamesMember,
  CodenamesView,
  CodenamesAction,
  SkyjoCell,
  SkyjoPlayerPublic,
  SkyjoView,
  SkyjoAction,
  GarticPhase,
  GarticPlayerScore,
  GarticMessage,
  GarticView,
  GarticAction,
  Devine9Team,
  Devine9Phase,
  Devine9Member,
  Devine9View,
  Devine9Action,
  SpyfallPhase,
  SpyfallReason,
  SpyfallView,
  SpyfallAction,
  ComplotsRole,
  ComplotsActKind,
  ComplotsPhase,
  ComplotsPlayerPublic,
  ComplotsPending,
  ComplotsEvent,
  ComplotsView,
  ComplotsAction,
  ChateauCell,
  ChateauPlayerPublic,
  ChateauPlayerScore,
  ChateauView,
  ChateauAction,
  LoveLetterCard,
  LoveLetterPlayerPublic,
  LoveLetterEvent,
  LoveLetterRoundResult,
  LoveLetterView,
  LoveLetterAction,
  UnoColor,
  UnoCardKind,
  UnoCard,
  UnoPlayerPublic,
  UnoView,
  UnoAction,
  DrawOp,
  SandboxShape,
  SandboxOp,
  GameView,
  GameAction,
} from "./games";
