// Explicit re-exports (not `export *`) so Node's ESM loader can statically
// detect every named export when the server runs the TS sources via tsx.
export { GAMES, gameById } from "./types";
export type {
  GameId,
  RoomPhase,
  Player,
  GameMeta,
  ChatMessage,
  RoomState,
} from "./types";
export type {
  PlayerIdentity,
  CreateRoomPayload,
  JoinRoomPayload,
  JoinResult,
  UpdateSettingsPayload,
  ClientToServerEvents,
  ServerToClientEvents,
  SocketData,
} from "./protocol";
export {
  DEFAULT_SETTINGS,
  BOMB_BOUNDS,
  BOMB_DIFFICULTIES,
  BOMB_BONUS_ALPHABET,
  CN_WORDS,
  D9_BOUNDS,
  sanitizeBombParty,
  sanitizeCodenames,
  sanitizeDevine9,
  sanitizeSettings,
} from "./settings";
export type {
  BombPartySettings,
  CodenamesSettings,
  Devine9Settings,
  AllSettings,
} from "./settings";
export { bullHeads } from "./games";
export type {
  Language,
  BombPartyView,
  BombPartyAction,
  PetitBacStage,
  PetitBacCell,
  PetitBacReviewCell,
  PetitBacView,
  PetitBacAction,
  SixPlayerPublic,
  SixTurnEntry,
  SixQuiPrendView,
  SixQuiPrendAction,
  CodenamesTeam,
  CodenamesCardColor,
  CodenamesRole,
  CodenamesPhase,
  CodenamesMember,
  CodenamesView,
  CodenamesAction,
  SkyjoCell,
  SkyjoPlayerPublic,
  SkyjoView,
  SkyjoAction,
  GarticPhase,
  GarticPlayerScore,
  GarticMessage,
  GarticView,
  GarticAction,
  Devine9Team,
  Devine9Phase,
  Devine9Member,
  Devine9View,
  Devine9Action,
  DrawOp,
  GameView,
  GameAction,
} from "./games";
